### ISSUE TITLE
ParcelJS doesn't parse .ejs files?

### ISSUE THREAD

**Issue by ancientaccount** [thoughtbyte/parcel-plugin-ejs#3]
Hello,

I just installed as requested the plugin by executing the command:
```bash
npm i -S parcel-plugin-ejs
```
Unfortunately my index.html file is empty.
Here's my script to start ParcelJS:
```bash
cross-env NODE_ENV=development parcel ./src/index.ejs
```

**Comment by capuche777** [comment]
Same here...

**Comment by alexdobsom** [comment]
the generated dist/index.html return empty :(
